In [5]:
import numpy as np
arr=[1,2,3,4,5]
print("Normal array",arr)
ar=np.array(arr)
print("Numpy array ",ar)


Normal array [1, 2, 3, 4, 5]
Numpy array  [1 2 3 4 5]


In [7]:
#Multi dimensional array
arr=np.array([[1,2,3],
            [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
#dimesion of array
arr.ndim

2

In [16]:
#print number of rows and columns
arr.shape

(2, 3)

In [17]:
#to print data type of array
arr.dtype


dtype('int32')

 zeros and ones create arrays of 0’s or 1’s

In [22]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [25]:
arr=np.zeros([3,4])
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr=np.ones([4,4])
print(arr)

arange is an array-valued version of the built-in Python range function

In [30]:
arr=np.arange(5)
print(arr)

[0 1 2 3 4]


You can explicitly convert or cast an array from one dtype to another using ndarray’s
astype method

In [42]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2=arr1.astype(np.float64)
print(arr2)
#string to int
arr3=np.array(['1','2','3'])
arr4=arr3.astype(np.int)
print(arr4)

[1. 2. 3. 4. 5.]
[1 2 3]


Operations between Arrays and Scalars

In [49]:
arr=np.array([[1,2,3],[4,5,6]])
#MULTIPLICATION
arr1=arr*arr
print(arr1)

#SUBTRACTION
arr1=arr-arr
print(arr1)

#
arr1=1/arr
print(arr1)




[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [51]:
arr=np.random.rand(10)
print(arr)

[0.62287805 0.5213537  0.72155944 0.99190403 0.69899801 0.72056797
 0.72337047 0.28435666 0.55020775 0.16836197]


In [63]:
print(arr1[0:,1])#all rows and second column
print(arr1[1:,1:])#second row 2 and 3 columns
print(arr1[1,2])#last row last column

[0.5 0.2]
[[0.2        0.16666667]]
0.16666666666666666


Transpose of array

In [67]:
arr = np.arange(15).reshape((3, 5))
print("making matrix from column vector")
print(arr)
print("TRANSPOSE")
print(arr.T)#TRANSPOSE

making matrix from column vector
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
TRANSPOSE
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
